version : '2'

services:
        
    handle:
        restart: "no"
        build: .
        links:
            - redis:redis
        depends_on:
            - redis    
    redis:
        image: redis:alpine
        expose:
            - "6379"
    
