services:
        
    handle:
        restart: "no"
        build: 
            context: ../../
            dockerfile: ./examples/python-mutex/Dockerfile
        links:
            - redis:redis
        depends_on:
            - redis

    redis:
        image: redis:alpine
        expose:
            - "6379"
    