services:
        
    handle:
        restart: "no"
        build: 
            context: ../../
            dockerfile: ./examples/python-hello-world/Dockerfile

        links:
            - redis:redis
        command: python -u hello-world.py
    
    redis:
        image: redis:alpine
        expose:
            - "6379"
    
