version : '2'

services:
        
    handle:
        restart: "no"
        build: .
        links:
            - redis:redis
        env_file: 
            - .env
        command: python -u manage.py handle_run 
    
    redis:
        image: redis:alpine
        expose:
            - "6379"
    
