version : '2'

services:
        
    handle:
        restart: "no"
        build: 
            context: ../../
            dockerfile: ./examples/python-hello-world/Dockerfile
        links:
            - redis:redis
        env_file: 
            - .env
    
    redis:
        image: redis:alpine
        expose:
            - "6379"
    
