version : '2'

services:
        
    handle:
        restart: "no"
        build: .
        links:
            - redis:redis
        command: python -u hello-world.py
    
    redis:
        image: redis:alpine
        expose:
            - "6379"
    
