version : '2'

services:
        
    handle:
        restart: "no"
        build: 
            context: ../../
            dockerfile: ./examples/python-hello-world-catchsig/Dockerfile
        links:
            - redis:redis
        env_file: 
            - .env
        command: python -u hello-world-catchsigterm.py
    
    redis:
        image: redis:alpine
        expose:
            - "6379"
    
